config/routes.rb
Rails.application.routes.draw do
  root 'todos#index'
  resources :todos
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/todo.rb
class Todo < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
  before_action :set_todo, only: %i[ show edit update destroy ]

  # GET /todos or /todos.json
  def index
    @todos = Todo.all.order(id: "DESC")
  end

  # GET /todos/1 or /todos/1.json
  def show
  end

  # GET /todos/new
  def new
    @todo = Todo.new
  end

  # GET /todos/1/edit
  def edit
  end

  # POST /todos or /todos.json
  def create
    @todo = Todo.new(todo_params)

    respond_to do |format|
      if @todo.save
        format.turbo_stream
        format.html { redirect_to todo_url(@todo), notice: "Todo was successfully created." }
        format.json { render :show, status: :created, location: @todo }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @todo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /todos/1 or /todos/1.json
  def update
    respond_to do |format|
      if @todo.update(todo_params)
        format.html { redirect_to todo_url(@todo), notice: "Todo was successfully updated." }
        format.json { render :show, status: :ok, location: @todo }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @todo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /todos/1 or /todos/1.json
  def destroy
    @todo.destroy

    respond_to do |format|
      format.turbo_stream
      format.html { redirect_to root_url, notice: "Todo was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_todo
      @todo = Todo.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def todo_params
      params.require(:todo).permit(:todo)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/todos_helper.rb
module TodosHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SampleTurboTodo</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <main class="container mx-auto mt-28 px-5 flex">
      <%= yield %>
    </main>
  </body>
</html>

app/views/todos/_form.html.erb
<%= form_with(model: todo, class: "contents") do |form| %>
  <% if todo.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(todo.errors.count, "error") %> prohibited this todo from being saved:</h2>

      <ul>
        <% todo.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="flex justify-between mb-2">
    <%= form.text_field :todo %>
    <div class="inline">
      <% if action_name == 'new' %>
        <%= form.submit 'Create', class: "rounded-lg py-2 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer hover:opacity-50" %>
      <% elsif action_name == 'edit' %>
        <%= form.submit 'Update', class: "rounded-lg py-2 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer hover:opacity-50" %>
      <% end %>
    </div>
  </div>

<% end %>

app/views/todos/_todo.html.erb
<%= turbo_frame_tag todo do %>
  <div class="flex justify-between items-center mb-4">
    <%= todo.todo %>
    <div>
      <%= link_to 'Edit', edit_todo_path(todo), class: "rounded-lg py-2 ml-2 px-5 bg-amber-400 text-white inline-block font-medium hover:opacity-50" %>
      <%= link_to 'Delete', todo_path(todo), data: { turbo_method: :delete }, class: "rounded-lg py-2 ml-2 px-5 bg-red-500 text-white inline-block font-medium hover:opacity-50" %>
    </div>
  </div>
<% end %>

app/views/todos/create.turbo_stream.erb
<%= turbo_stream.prepend 'todos', @todo %>

app/views/todos/destroy.turbo_stream.erb
<%= turbo_stream.remove @todo %>

app/views/todos/edit.html.erb
<%= turbo_frame_tag @todo do %>
  <%= render "form", todo: @todo %>
<% end %>

app/views/todos/index.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <div class="flex flex-col">
    <%= turbo_frame_tag 'new', src: new_todo_path %>
  </div>

  <div id="todos" class="min-w-full">
    <%= turbo_frame_tag 'todos' do %>
      <%= render @todos %>
    <% end %>
    </div>
</div>

app/views/todos/new.html.erb
<%= turbo_frame_tag 'new' do %>
  <div class="mb-8">
    <h1 class="font-bold text-4xl mb-2">Todo</h1>
    <%= render "form", todo: @todo %>
  </div>
<% end %>

app/views/todos/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <%= render @todo %>

    <%= link_to 'Edit this todo', edit_todo_path(@todo), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <div class="inline-block ml-2">
      <%= button_to 'Destroy this todo', todo_path(@todo), method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
    </div>
    <%= link_to 'Back to todos', todos_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  </div>
</div>

app/views/todos/update.turbo_stream.erb
<%= turbo_stream.replace @todo %>